"""Initial schema

Revision ID: 353583bd610f
Revises: 
Create Date: 2026-01-18 22:53:21.757250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '353583bd610f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_brief_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('headline_validated', sa.Boolean(), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=False),
    sa.Column('stable_count', sa.Integer(), nullable=False),
    sa.Column('improving_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_brief_snapshots_as_of_date'), 'portfolio_brief_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_portfolio_brief_snapshots_portfolio_id'), 'portfolio_brief_snapshots', ['portfolio_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_portfolio_id'), 'properties', ['portfolio_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_portfolio_id'), 'tenants', ['portfolio_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('memo_what_disclosed', sa.Text(), nullable=True),
    sa.Column('memo_key_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memo_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('memo_validated', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('suite_label', sa.String(length=100), nullable=True),
    sa.Column('rent_share_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_property_id'), 'leases', ['property_id'], unique=False)
    op.create_index(op.f('ix_leases_tenant_id'), 'leases', ['tenant_id'], unique=False)
    op.create_table('tenant_score_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'as_of_date', name='uq_tenant_snapshot_date')
    )
    op.create_index(op.f('ix_tenant_score_snapshots_as_of_date'), 'tenant_score_snapshots', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_tenant_score_snapshots_tenant_id'), 'tenant_score_snapshots', ['tenant_id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('page_reference', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sources_event_id'), 'evidence_sources', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_sources_event_id'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_tenant_score_snapshots_tenant_id'), table_name='tenant_score_snapshots')
    op.drop_index(op.f('ix_tenant_score_snapshots_as_of_date'), table_name='tenant_score_snapshots')
    op.drop_table('tenant_score_snapshots')
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_property_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_tenants_portfolio_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_properties_portfolio_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_portfolio_brief_snapshots_portfolio_id'), table_name='portfolio_brief_snapshots')
    op.drop_index(op.f('ix_portfolio_brief_snapshots_as_of_date'), table_name='portfolio_brief_snapshots')
    op.drop_table('portfolio_brief_snapshots')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
