"""add_logo_url_to_tenants

Revision ID: 44c6adc68abd
Revises: d0ed6397573a
Create Date: 2026-01-20 20:02:17.502272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c6adc68abd'
down_revision: Union[str, None] = 'd0ed6397573a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###
