"""Add exec layer and memo action fields

Revision ID: d0ed6397573a
Revises: 353583bd610f
Create Date: 2026-01-19 10:46:39.982012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0ed6397573a'
down_revision: Union[str, None] = '353583bd610f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('memo_why_it_matters', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('memo_recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('memo_what_to_watch', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('portfolio_brief_snapshots', sa.Column('portfolio_verdict', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('portfolio_brief_snapshots', sa.Column('narrative_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('portfolio_brief_snapshots', sa.Column('concentration_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('portfolio_brief_snapshots', sa.Column('exec_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_brief_snapshots', 'exec_questions')
    op.drop_column('portfolio_brief_snapshots', 'concentration_insights')
    op.drop_column('portfolio_brief_snapshots', 'narrative_bullets')
    op.drop_column('portfolio_brief_snapshots', 'portfolio_verdict')
    op.drop_column('events', 'memo_what_to_watch')
    op.drop_column('events', 'memo_recommended_actions')
    op.drop_column('events', 'memo_why_it_matters')
    # ### end Alembic commands ###
