import type { BriefResponse, Tenant, Event, TenantDetailResponse, Evidence } from "@/types";

// Mock Brief Response
export const mockBrief: BriefResponse = {
  id: "brief-001",
  asOfDate: "2026-01-17",
  headline: "3 tenants disclosed material events this week. 4 status changes from last week.",
  updatedAt: "2026-01-17T06:00:00-06:00",
  statusCounts: {
    critical: 3,
    watch: 6,
    stable: 18,
    improving: 3,
  },
  statusChanges: {
    toWatchOrCritical: [
      {
        tenantId: "tenant-apex",
        tenantName: "Apex Retail Group",
        previousStatus: "watch",
        newStatus: "critical",
        eventId: "event-001",
        eventHeadline: "Disclosed going concern language in 10-Q filing",
      },
      {
        tenantId: "tenant-northstar",
        tenantName: "Northstar Apparel",
        previousStatus: "watch",
        newStatus: "critical",
        eventId: "event-002",
        eventHeadline: "Filed Chapter 11 bankruptcy petition",
      },
      {
        tenantId: "tenant-meridian",
        tenantName: "Meridian Healthcare",
        previousStatus: "stable",
        newStatus: "watch",
        eventId: "event-003",
        eventHeadline: "Engaged restructuring advisor per 8-K",
      },
      {
        tenantId: "tenant-techflow",
        tenantName: "TechFlow Solutions",
        previousStatus: "stable",
        newStatus: "watch",
        eventId: "event-004",
        eventHeadline: "Disclosed covenant waiver in credit agreement",
      },
    ],
    toImproving: [
      {
        tenantId: "tenant-bluesky",
        tenantName: "BlueSky Manufacturing",
        previousStatus: "watch",
        newStatus: "improving",
        eventId: "event-005",
        eventHeadline: "Completed debt refinancing, extended maturities to 2030",
      },
    ],
    unchanged: 25,
  },
  recentEvents: [
    {
      id: "event-001",
      tenantId: "tenant-apex",
      tenantName: "Apex Retail Group",
      eventType: "sec_filing",
      eventDate: "2026-01-15",
      headline: "Disclosed going concern language and covenant breach in Q3 10-Q filing",
      summary: "The company filed its Q3 2025 10-Q with the SEC, including language indicating substantial doubt about its ability to continue as a going concern.",
      evidenceCount: 4,
      properties: [
        { id: "prop-park", name: "Park Plaza" },
        { id: "prop-south", name: "Southfield" },
      ],
    },
    {
      id: "event-002",
      tenantId: "tenant-northstar",
      tenantName: "Northstar Apparel",
      eventType: "court_filing",
      eventDate: "2026-01-14",
      headline: "Filed voluntary Chapter 11 bankruptcy petition in Delaware",
      summary: "Northstar Apparel Inc. filed a voluntary petition for reorganization under Chapter 11 of the Bankruptcy Code.",
      evidenceCount: 3,
      properties: [
        { id: "prop-metro", name: "Metropolitan Center" },
      ],
    },
    {
      id: "event-003",
      tenantId: "tenant-meridian",
      tenantName: "Meridian Healthcare",
      eventType: "sec_filing",
      eventDate: "2026-01-13",
      headline: "Engaged Alvarez & Marsal as restructuring advisor per 8-K disclosure",
      summary: "The company disclosed the engagement of a restructuring advisor to assist with balance sheet optimization.",
      evidenceCount: 2,
      properties: [
        { id: "prop-gateway", name: "Gateway Medical" },
        { id: "prop-harbor", name: "Harbor Point" },
      ],
    },
    {
      id: "event-005",
      tenantId: "tenant-bluesky",
      tenantName: "BlueSky Manufacturing",
      eventType: "press_release",
      eventDate: "2026-01-12",
      headline: "Completed $150M debt refinancing, extended maturities to 2030",
      summary: "BlueSky announced successful completion of refinancing, improving liquidity position and extending debt maturities.",
      evidenceCount: 2,
      properties: [
        { id: "prop-lakewood", name: "Lakewood Industrial" },
      ],
    },
  ],
  coverage: {
    tenantsMonitored: 30,
    tenantsWithDisclosures: 6,
    sources: ["SEC EDGAR", "Reuters", "Court Records"],
    asOfDate: "2026-01-17",
  },
};

// Mock Tenant Detail
export const mockTenantDetail: TenantDetailResponse = {
  tenant: {
    id: "tenant-apex",
    name: "Apex Retail Group",
    ticker: "APEX",
    cik: "0001234567",
    industry: "Retail",
    entityType: "public",
    status: "critical",
    propertyCount: 2,
  },
  properties: [
    {
      id: "prop-park",
      name: "Park Plaza Shopping Center",
      city: "Dallas",
      state: "TX",
      assetClass: "Retail",
      tenantCount: 4,
      eventsCount: 1,
    },
    {
      id: "prop-south",
      name: "Southfield Retail Center",
      city: "Houston",
      state: "TX",
      assetClass: "Retail",
      tenantCount: 6,
      eventsCount: 1,
    },
  ],
  events: [
    {
      id: "event-001",
      tenantId: "tenant-apex",
      tenantName: "Apex Retail Group",
      eventType: "sec_filing",
      eventDate: "2026-01-15",
      headline: "Disclosed going concern language and covenant breach in Q3 10-Q filing",
      summary: "The company filed its Q3 2025 10-Q with the SEC, including language indicating substantial doubt about its ability to continue as a going concern.",
      memo: {
        whatWasDisclosed: "The company filed its Q3 2025 10-Q with the SEC, including language indicating substantial doubt about its ability to continue as a going concern. The filing also discloses that the company was not in compliance with its debt service coverage ratio covenant as of September 30, 2025.",
        keyDetails: [
          { fact: "Going concern language included in Note 1 to financial statements", citation: "10-Q, p.12" },
          { fact: "Debt service coverage ratio covenant breached as of Sept 30, 2025", citation: "10-Q, p.47" },
          { fact: "Same-store sales declined 18% year-over-year", citation: "10-Q, p.23" },
          { fact: "Company in active discussions with lenders regarding amendments", citation: "8-K, Item 8.01" },
        ],
        context: [
          "This tenant occupies space at 2 properties in the portfolio",
          "Anchor tenant at both Park Plaza and Southfield Retail Center",
          "This is the second credit agreement amendment disclosed in the past 12 months",
        ],
      },
      evidenceCount: 4,
      properties: [
        { id: "prop-park", name: "Park Plaza" },
        { id: "prop-south", name: "Southfield" },
      ],
    },
  ],
};

// Mock Evidence
export const mockEvidence: Evidence[] = [
  {
    id: "ev-001",
    eventId: "event-001",
    sourceType: "sec_filing",
    title: "Form 10-Q Q3 2025",
    publisher: "SEC EDGAR",
    date: "2026-01-14",
    url: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001234567",
    excerpt: "These conditions raise substantial doubt about the Company's ability to continue as a going concern within one year after the date these financial statements are issued.",
    pageReference: "p.12",
  },
  {
    id: "ev-002",
    eventId: "event-001",
    sourceType: "sec_filing",
    title: "Form 8-K Current Report",
    publisher: "SEC EDGAR",
    date: "2026-01-15",
    url: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001234567",
    excerpt: "The Company has entered into discussions with its lenders regarding potential amendments to its credit facilities.",
  },
  {
    id: "ev-003",
    eventId: "event-001",
    sourceType: "news",
    title: "Apex Retail warns of going concern risk amid declining sales",
    publisher: "Reuters",
    date: "2026-01-15",
    url: "https://reuters.com/example",
    excerpt: "Apex Retail Group Inc disclosed substantial doubt about its ability to continue operating...",
  },
  {
    id: "ev-004",
    eventId: "event-001",
    sourceType: "news",
    title: "Retail sector struggles continue as Apex reports covenant breach",
    publisher: "Wall Street Journal",
    date: "2026-01-15",
    url: "https://wsj.com/example",
  },
];

// Mock Tenants List
export const mockTenants: Tenant[] = [
  {
    id: "tenant-apex",
    name: "Apex Retail Group",
    ticker: "APEX",
    industry: "Retail",
    entityType: "public",
    status: "critical",
    propertyCount: 2,
    latestEvent: {
      id: "event-001",
      eventType: "sec_filing",
      headline: "Going concern disclosed in 10-Q",
      date: "2026-01-15",
    },
  },
  {
    id: "tenant-northstar",
    name: "Northstar Apparel",
    ticker: "NSTR",
    industry: "Retail",
    entityType: "public",
    status: "critical",
    propertyCount: 1,
    latestEvent: {
      id: "event-002",
      eventType: "court_filing",
      headline: "Chapter 11 bankruptcy filed",
      date: "2026-01-14",
    },
  },
  {
    id: "tenant-urban",
    name: "Urban Fitness Centers",
    industry: "Fitness",
    entityType: "private",
    status: "critical",
    propertyCount: 3,
    latestEvent: {
      id: "event-006",
      eventType: "news",
      headline: "Announced closure of 15 locations",
      date: "2026-01-13",
    },
  },
  {
    id: "tenant-meridian",
    name: "Meridian Healthcare",
    ticker: "MHCS",
    industry: "Healthcare",
    entityType: "public",
    status: "watch",
    propertyCount: 2,
    latestEvent: {
      id: "event-003",
      eventType: "sec_filing",
      headline: "Engaged restructuring advisor",
      date: "2026-01-13",
    },
  },
  {
    id: "tenant-bluesky",
    name: "BlueSky Manufacturing",
    ticker: "BSKY",
    industry: "Manufacturing",
    entityType: "public",
    status: "improving",
    propertyCount: 1,
    latestEvent: {
      id: "event-005",
      eventType: "press_release",
      headline: "Completed debt refinancing",
      date: "2026-01-12",
    },
  },
];
